language: node_js
env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: "qg57AlPHJd1YeBt+k8Dei2MEQU2m6BIBXrIVqUxKt2I7ECw4bUGsKJulU7Rh0MzAi/5JA1kEmdZdyaiWMRnv/scyb+oL1JpcWuo8O6GAiOIr3nyQVL8nL3wdXIqLkhhVv9s7K8MwHJ8glYfGmhCdZTqnlOcAnXyO00XxwGMaWaE="
    - BMSPEC_HOME=../bmspec
node_js:
  - "0.10"
before_script:
  - 'git clone https://github.com/bemusic/bms-spec.git $BMSPEC_HOME'
after_success:
  - 'cat coverage/lcov.info | ./node_modules/.bin/codeclimate'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/31893c5fbae5d66e0a6f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true      # default: false
