language: node_js
node_js:
- 5
after_success:
- npm install -g codecov
- codecov
deploy:
  provider: npm
  email: org.yi.dttvb@gmail.com
  api_key:
    secure: U0KQnuriVGLnKL9XnRmoa18tfL4wZ3xs9rRkEk7gPQVZ6VCvi2ssq9eC1XAAZdvatVTiPArrwVd65lCDRAbumKHYHu29NJ/QY2QhOfcRqpoT83FoDYPQJ0UrXfAcmfnao4IEwRP/g//IX2XIyjcnySJvxqLnr1JEuFmRprao7BTk7gxWP6WhbidWaHuht6CCo3mpl7PcB3MBkMJOVJEORjnnxMsn8Dq7ORwzaSIJgql1mO0NLPm1gXSqEgdhFv9ZBjm1V3vS3CewnLOADLhBNKhY9NhYJytEHIMuacJWcn7oTK7FohFJogJQ3SNgtkZHD8HmHmk2HCuKC1zgbO0muXWJftm2Dmq/VJ2XOOE8R2bOE6JqEzLQkLFNfZmm78r7YIFcSKbsg8plbI/dCrXvMlOupkBgR0ZP4tcaepj2bKu7PpRcT/sr+uz7rQwrvHgu9G2LaPXMvRWMPvFVXefKq/PbIMjV/3NAM10y6LmD3BjRCYMczbMTFSlYGx/5+9VfW6P88YCPUoaZ6DOfPQXHUgSdDue35wwmCtKSNNJtMmqQVSvMv+uGwdVQFxcoktTPU7tHukQg6r2ttLs0Jrw6YkbzuYV0eWxdARhnvHrLR2dZQ5mkUbpVKHtYsRpFvSn5yw64ZWRzlh13B4sy0Dxkk22nCKhfbsYKQoa48Fp2yZ0=
  on:
    tags: true
    repo: bemusic/bemuse-notechart
